=== pjs3065/Advanced-Web-Programming/Ex2/tvschedule/tvschedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="TVSCHEDULE">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CHANNEL" maxOccurs="unbounded"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BANNER" type="xs:string" />
							<xs:element name="DAY" maxOccurs="unbounded"
								minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DATE" type="xs:string" />
										<xs:choice>
											<xs:element name="HOLYDAY" type="xs:string"
												maxOccurs="unbounded" minOccurs="1" />
											<xs:element name="PROGRAMSLOT" maxOccurs="unbounded"
												minOccurs="1">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="TIME" type="xs:string" />
														<xs:element name="TITLE">
															<xs:complexType>
																<xs:simpleContent>
																	<xs:extension base="xs:string">
																		<xs:attribute name="RATING" type="xs:string" />
																		<xs:attribute name="LANGUAGE" type="xs:string" />
																	</xs:extension>
																</xs:simpleContent>
															</xs:complexType>
														</xs:element>
														<xs:element name="DESCRIPTION" type="xs:string"
															maxOccurs="1" minOccurs="0" />
													</xs:sequence>
													<xs:attribute name="VTR" type="xs:string" />
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="CHAN" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="NAME" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pjs3065/Advanced-Web-Programming/Ex2/tvschedule/tvschedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<TVSCHEDULE NAME="MBC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tvschedule.xsd">
	<CHANNEL CHAN="11">
		<BANNER>banner1</BANNER>
		<DAY>
			<DATE>Monday</DATE>
			<HOLYDAY>YES</HOLYDAY>
		</DAY>
	</CHANNEL>
	
	<CHANNEL CHAN="11">
		<BANNER>banner2</BANNER>
		<DAY>
			<DATE>Monday</DATE>
			<PROGRAMSLOT VTR="VTR1">
				<TIME>7:00</TIME>
				<TITLE RATING="33">7am News</TITLE>
				<DESCRIPTION>Morning news1</DESCRIPTION>
			</PROGRAMSLOT>
			
			<PROGRAMSLOT VTR="VTR2">
				<TIME>8:00</TIME>
				<TITLE LANGUAGE="KOREA">8am News</TITLE>
				<DESCRIPTION>Morning news2</DESCRIPTION>
			</PROGRAMSLOT>
		</DAY>
	</CHANNEL>
</TVSCHEDULE>
