=== pjs3065/Advanced-Web-Programming/Ex2/newspaper/newspaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="NEWSPAPER">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ARTICLE" maxOccurs="unbounded"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HEADLINE" type="xs:string" />
							<xs:element name="BYLINE" type="xs:string" />
							<xs:element name="LEAD" type="xs:string" />
							<xs:element name="BODY" type="xs:string" />
							<xs:element name="NOTES" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="AUTHOR" type="xs:string" use="required" />
						<xs:attribute name="EDITOR" type="xs:string" />
						<xs:attribute name="DATE" type="xs:string" />
						<xs:attribute name="EDITION" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>

		</xs:complexType>
	</xs:element>
</xs:schema>

=== pjs3065/Advanced-Web-Programming/Ex2/newspaper/newspaper.xml
<?xml version="1.0" encoding="UTF-8"?>
<NEWSPAPER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="newspaper.xsd">
	
	<ARTICLE AUTHOR="author1" EDITOR="editor1" DATE="date1" EDITION="edition1">
		<HEADLINE>headline1</HEADLINE>
		<BYLINE>byline1</BYLINE>
		<LEAD>lead1</LEAD>
		<BODY>body1</BODY>
		<NOTES>notes1</NOTES>
	</ARTICLE>

	<ARTICLE AUTHOR="author2">
		<HEADLINE>headline2</HEADLINE>
		<BYLINE>byline2</BYLINE>
		<LEAD>lead2</LEAD>
		<BODY>body2</BODY>
		<NOTES>notes2</NOTES>
	</ARTICLE>
</NEWSPAPER>
